create table if not exists countries (
    code char(2) primary key,
    name text not null
);

create table if not exists languages (
    code char(2) primary key,
    label text not null,
    flag text not null
);

insert into countries (code, name) values
('AF','Afghanistan'),
('AX','Åland Islands'),
('AL','Albania'),
('DZ','Algeria'),
('AS','American Samoa'),
('AD','Andorra'),
('AO','Angola'),
('AI','Anguilla'),
('AQ','Antarctica'),
('AG','Antigua and Barbuda'),
('AR','Argentina'),
('AM','Armenia'),
('AW','Aruba'),
('AU','Australia'),
('AT','Austria'),
('AZ','Azerbaijan'),
('BS','Bahamas'),
('BH','Bahrain'),
('BD','Bangladesh'),
('BB','Barbados'),
('BY','Belarus'),
('BE','Belgium'),
('BZ','Belize'),
('BJ','Benin'),
('BM','Bermuda'),
('BT','Bhutan'),
('BO','Bolivia, Plurinational State of'),
('BQ','Bonaire, Sint Eustatius and Saba'),
('BA','Bosnia and Herzegovina'),
('BW','Botswana'),
('BV','Bouvet Island'),
('BR','Brazil'),
('IO','British Indian Ocean Territory'),
('BN','Brunei Darussalam'),
('BG','Bulgaria'),
('BF','Burkina Faso'),
('BI','Burundi'),
('CV','Cabo Verde'),
('KH','Cambodia'),
('CM','Cameroon'),
('CA','Canada'),
('KY','Cayman Islands'),
('CF','Central African Republic'),
('TD','Chad'),
('CL','Chile'),
('CN','China'),
('CX','Christmas Island'),
('CC','Cocos (Keeling) Islands'),
('CO','Colombia'),
('KM','Comoros'),
('CG','Congo'),
('CD','Congo, Democratic Republic of the'),
('CK','Cook Islands'),
('CR','Costa Rica'),
('CI','Côte d''Ivoire'),
('HR','Croatia'),
('CU','Cuba'),
('CW','Curaçao'),
('CY','Cyprus'),
('CZ','Czechia'),
('DK','Denmark'),
('DJ','Djibouti'),
('DM','Dominica'),
('DO','Dominican Republic'),
('EC','Ecuador'),
('EG','Egypt'),
('SV','El Salvador'),
('GQ','Equatorial Guinea'),
('ER','Eritrea'),
('EE','Estonia'),
('SZ','Eswatini'),
('ET','Ethiopia'),
('FK','Falkland Islands (Malvinas)'),
('FO','Faroe Islands'),
('FJ','Fiji'),
('FI','Finland'),
('FR','France'),
('GF','French Guiana'),
('PF','French Polynesia'),
('TF','French Southern Territories'),
('GA','Gabon'),
('GM','Gambia'),
('GE','Georgia'),
('DE','Germany'),
('GH','Ghana'),
('GI','Gibraltar'),
('GR','Greece'),
('GL','Greenland'),
('GD','Grenada'),
('GP','Guadeloupe'),
('GU','Guam'),
('GT','Guatemala'),
('GG','Guernsey'),
('GN','Guinea'),
('GW','Guinea-Bissau'),
('GY','Guyana'),
('HT','Haiti'),
('HM','Heard Island and McDonald Islands'),
('VA','Holy See'),
('HN','Honduras'),
('HK','Hong Kong'),
('HU','Hungary'),
('IS','Iceland'),
('IN','India'),
('ID','Indonesia'),
('IR','Iran, Islamic Republic of'),
('IQ','Iraq'),
('IE','Ireland'),
('IM','Isle of Man'),
('IL','Israel'),
('IT','Italy'),
('JM','Jamaica'),
('JP','Japan'),
('JE','Jersey'),
('JO','Jordan'),
('KZ','Kazakhstan'),
('KE','Kenya'),
('KI','Kiribati'),
('KP','Korea, Democratic People''s Republic of'),
('KR','Korea, Republic of'),
('KW','Kuwait'),
('KG','Kyrgyzstan'),
('LA','Lao People''s Democratic Republic'),
('LV','Latvia'),
('LB','Lebanon'),
('LS','Lesotho'),
('LR','Liberia'),
('LY','Libya'),
('LI','Liechtenstein'),
('LT','Lithuania'),
('LU','Luxembourg'),
('MO','Macao'),
('MG','Madagascar'),
('MW','Malawi'),
('MY','Malaysia'),
('MV','Maldives'),
('ML','Mali'),
('MT','Malta'),
('MH','Marshall Islands'),
('MQ','Martinique'),
('MR','Mauritania'),
('MU','Mauritius'),
('YT','Mayotte'),
('MX','Mexico'),
('FM','Micronesia, Federated States of'),
('MD','Moldova, Republic of'),
('MC','Monaco'),
('MN','Mongolia'),
('ME','Montenegro'),
('MS','Montserrat'),
('MA','Morocco'),
('MZ','Mozambique'),
('MM','Myanmar'),
('NA','Namibia'),
('NR','Nauru'),
('NP','Nepal'),
('NL','Netherlands'),
('NC','New Caledonia'),
('NZ','New Zealand'),
('NI','Nicaragua'),
('NE','Niger'),
('NG','Nigeria'),
('NU','Niue'),
('NF','Norfolk Island'),
('MK','North Macedonia'),
('MP','Northern Mariana Islands'),
('NO','Norway'),
('OM','Oman'),
('PK','Pakistan'),
('PW','Palau'),
('PS','Palestine, State of'),
('PA','Panama'),
('PG','Papua New Guinea'),
('PY','Paraguay'),
('PE','Peru'),
('PH','Philippines'),
('PN','Pitcairn'),
('PL','Poland'),
('PT','Portugal'),
('PR','Puerto Rico'),
('QA','Qatar'),
('RE','Réunion'),
('RO','Romania'),
('RU','Russian Federation'),
('RW','Rwanda'),
('BL','Saint Barthélemy'),
('SH','Saint Helena, Ascension and Tristan da Cunha'),
('KN','Saint Kitts and Nevis'),
('LC','Saint Lucia'),
('MF','Saint Martin (French part)'),
('PM','Saint Pierre and Miquelon'),
('VC','Saint Vincent and the Grenadines'),
('WS','Samoa'),
('SM','San Marino'),
('ST','Sao Tome and Principe'),
('SA','Saudi Arabia'),
('SN','Senegal'),
('RS','Serbia'),
('SC','Seychelles'),
('SL','Sierra Leone'),
('SG','Singapore'),
('SX','Sint Maarten (Dutch part)'),
('SK','Slovakia'),
('SI','Slovenia'),
('SB','Solomon Islands'),
('SO','Somalia'),
('ZA','South Africa'),
('GS','South Georgia and the South Sandwich Islands'),
('SS','South Sudan'),
('ES','Spain'),
('LK','Sri Lanka'),
('SD','Sudan'),
('SR','Suriname'),
('SJ','Svalbard and Jan Mayen'),
('SE','Sweden'),
('CH','Switzerland'),
('SY','Syrian Arab Republic'),
('TW','Taiwan, Province of China'),
('TJ','Tajikistan'),
('TZ','Tanzania, United Republic of'),
('TH','Thailand'),
('TL','Timor-Leste'),
('TG','Togo'),
('TK','Tokelau'),
('TO','Tonga'),
('TT','Trinidad and Tobago'),
('TN','Tunisia'),
('TR','Türkiye'),
('TM','Turkmenistan'),
('TC','Turks and Caicos Islands'),
('TV','Tuvalu'),
('UG','Uganda'),
('UA','Ukraine'),
('AE','United Arab Emirates'),
('GB','United Kingdom of Great Britain and Northern Ireland'),
('US','United States of America'),
('UM','United States Minor Outlying Islands'),
('UY','Uruguay'),
('UZ','Uzbekistan'),
('VU','Vanuatu'),
('VE','Venezuela, Bolivarian Republic of'),
('VN','Viet Nam'),
('VG','Virgin Islands (British)'),
('VI','Virgin Islands (U.S.)'),
('WF','Wallis and Futuna'),
('EH','Western Sahara'),
('YE','Yemen'),
('ZM','Zambia'),
('ZW','Zimbabwe');

insert into languages (code, label, flag) values
('aa','Afar','🇦🇦'),
('ab','Abkhaz','🇦🇧'),
('ae','Avestan','🇦🇪'),
('af','Afrikaans','🇦🇫'),
('ak','Akan','🇦🇰'),
('am','Amharic','🇦🇲'),
('an','Aragonese','🇦🇳'),
('ar','Arabic','🇦🇷'),
('as','Assamese','🇦🇸'),
('av','Avaric','🇦🇻'),
('ay','Aymara','🇦🇾'),
('az','Azerbaijani','🇦🇿'),
('ba','Bashkir','🇧🇦'),
('be','Belarusian','🇧🇪'),
('bg','Bulgarian','🇧🇬'),
('bh','Bihari','🇧🇭'),
('bi','Bislama','🇧🇮'),
('bm','Bambara','🇧🇲'),
('bn','Bengali, Bangla','🇧🇳'),
('bo','Tibetan Standard, Tibetan, Central','🇧🇴'),
('br','Breton','🇧🇷'),
('bs','Bosnian','🇧🇸'),
('ca','Catalan','🇨🇦'),
('ce','Chechen','🇨🇪'),
('ch','Chamorro','🇨🇭'),
('co','Corsican','🇨🇴'),
('cr','Cree','🇨🇷'),
('cs','Czech','🇨🇸'),
('cu','Old Church Slavonic, Church Slavonic, Old Bulgarian','🇨🇺'),
('cv','Chuvash','🇨🇻'),
('cy','Welsh','🇨🇾'),
('da','Danish','🇩🇦'),
('de','German','🇩🇪'),
('dv','Divehi, Dhivehi, Maldivian','🇩🇻'),
('dz','Dzongkha','🇩🇿'),
('ee','Ewe','🇪🇪'),
('el','Greek (modern)','🇪🇱'),
('en','English','🇪🇳'),
('eo','Esperanto','🇪🇴'),
('es','Spanish','🇪🇸'),
('et','Estonian','🇪🇹'),
('eu','Basque','🇪🇺'),
('fa','Persian (Farsi)','🇫🇦'),
('ff','Fula, Fulah, Pulaar, Pular','🇫🇫'),
('fi','Finnish','🇫🇮'),
('fj','Fijian','🇫🇯'),
('fo','Faroese','🇫🇴'),
('fr','French','🇫🇷'),
('fy','Western Frisian','🇫🇾'),
('ga','Irish','🇬🇦'),
('gd','Scottish Gaelic, Gaelic','🇬🇩'),
('gl','Galician','🇬🇱'),
('gn','Guaraní','🇬🇳'),
('gu','Gujarati','🇬🇺'),
('gv','Manx','🇬🇻'),
('ha','Hausa','🇭🇦'),
('he','Hebrew (modern)','🇭🇪'),
('hi','Hindi','🇭🇮'),
('ho','Hiri Motu','🇭🇴'),
('hr','Croatian','🇭🇷'),
('ht','Haitian, Haitian Creole','🇭🇹'),
('hu','Hungarian','🇭🇺'),
('hy','Armenian','🇭🇾'),
('hz','Herero','🇭🇿'),
('ia','Interlingua','🇮🇦'),
('id','Indonesian','🇮🇩'),
('ie','Interlingue','🇮🇪'),
('ig','Igbo','🇮🇬'),
('ii','Nuosu','🇮🇮'),
('ik','Inupiaq','🇮🇰'),
('io','Ido','🇮🇴'),
('is','Icelandic','🇮🇸'),
('it','Italian','🇮🇹'),
('iu','Inuktitut','🇮🇺'),
('ja','Japanese','🇯🇦'),
('jv','Javanese','🇯🇻'),
('ka','Georgian','🇰🇦'),
('kg','Kongo','🇰🇬'),
('ki','Kikuyu, Gikuyu','🇰🇮'),
('kj','Kwanyama, Kuanyama','🇰🇯'),
('kk','Kazakh','🇰🇰'),
('kl','Kalaallisut, Greenlandic','🇰🇱'),
('km','Khmer','🇰🇲'),
('kn','Kannada','🇰🇳'),
('ko','Korean','🇰🇴'),
('kr','Kanuri','🇰🇷'),
('ks','Kashmiri','🇰🇸'),
('ku','Kurdish','🇰🇺'),
('kv','Komi','🇰🇻'),
('kw','Cornish','🇰🇼'),
('ky','Kyrgyz','🇰🇾'),
('la','Latin','🇱🇦'),
('lb','Luxembourgish, Letzeburgesch','🇱🇧'),
('lg','Ganda','🇱🇬'),
('li','Limburgish, Limburgan, Limburger','🇱🇮'),
('ln','Lingala','🇱🇳'),
('lo','Lao','🇱🇴'),
('lt','Lithuanian','🇱🇹'),
('lu','Luba-Katanga','🇱🇺'),
('lv','Latvian','🇱🇻'),
('mg','Malagasy','🇲🇬'),
('mh','Marshallese','🇲🇭'),
('mi','Māori','🇲🇮'),
('mk','Macedonian','🇲🇰'),
('ml','Malayalam','🇲🇱'),
('mn','Mongolian','🇲🇳'),
('mr','Marathi (Marāṭhī)','🇲🇷'),
('ms','Malay','🇲🇸'),
('mt','Maltese','🇲🇹'),
('my','Burmese','🇲🇾'),
('na','Nauruan','🇳🇦'),
('nb','Norwegian Bokmål','🇳🇧'),
('nd','Northern Ndebele','🇳🇩'),
('ne','Nepali','🇳🇪'),
('ng','Ndonga','🇳🇬'),
('nl','Dutch','🇳🇱'),
('nn','Norwegian Nynorsk','🇳🇳'),
('no','Norwegian','🇳🇴'),
('nr','Southern Ndebele','🇳🇷'),
('nv','Navajo, Navaho','🇳🇻'),
('ny','Chichewa, Chewa, Nyanja','🇳🇾'),
('oc','Occitan','🇴🇨'),
('oj','Ojibwe, Ojibwa','🇴🇯'),
('om','Oromo','🇴🇲'),
('or','Oriya','🇴🇷'),
('os','Ossetian, Ossetic','🇴🇸'),
('pa','(Eastern) Punjabi','🇵🇦'),
('pi','Pāli','🇵🇮'),
('pl','Polish','🇵🇱'),
('ps','Pashto, Pushto','🇵🇸'),
('pt','Portuguese','🇵🇹'),
('qu','Quechua','🇶🇺'),
('rm','Romansh','🇷🇲'),
('rn','Kirundi','🇷🇳'),
('ro','Romanian','🇷🇴'),
('ru','Russian','🇷🇺'),
('rw','Kinyarwanda','🇷🇼'),
('sa','Sanskrit (Saṁskṛta)','🇸🇦'),
('sc','Sardinian','🇸🇨'),
('sd','Sindhi','🇸🇩'),
('se','Northern Sami','🇸🇪'),
('sg','Sango','🇸🇬'),
('si','Sinhalese, Sinhala','🇸🇮'),
('sk','Slovak','🇸🇰'),
('sl','Slovene','🇸🇱'),
('sm','Samoan','🇸🇲'),
('sn','Shona','🇸🇳'),
('so','Somali','🇸🇴'),
('sq','Albanian','🇸🇶'),
('sr','Serbian','🇸🇷'),
('ss','Swati','🇸🇸'),
('st','Southern Sotho','🇸🇹'),
('su','Sundanese','🇸🇺'),
('sv','Swedish','🇸🇻'),
('sw','Swahili','🇸🇼'),
('ta','Tamil','🇹🇦'),
('te','Telugu','🇹🇪'),
('tg','Tajik','🇹🇬'),
('th','Thai','🇹🇭'),
('ti','Tigrinya','🇹🇮'),
('tk','Turkmen','🇹🇰'),
('tl','Tagalog','🇹🇱'),
('tn','Tswana','🇹🇳'),
('to','Tonga (Tonga Islands)','🇹🇴'),
('tr','Turkish','🇹🇷'),
('ts','Tsonga','🇹🇸'),
('tt','Tatar','🇹🇹'),
('tw','Twi','🇹🇼'),
('ty','Tahitian','🇹🇾'),
('ug','Uyghur','🇺🇬'),
('uk','Ukrainian','🇺🇰'),
('ur','Urdu','🇺🇷'),
('uz','Uzbek','🇺🇿'),
('ve','Venda','🇻🇪'),
('vi','Vietnamese','🇻🇮'),
('vo','Volapük','🇻🇴'),
('wa','Walloon','🇼🇦'),
('wo','Wolof','🇼🇴'),
('xh','Xhosa','🇽🇭'),
('yi','Yiddish','🇾🇮'),
('yo','Yoruba','🇾🇴'),
('za','Zhuang, Chuang','🇿🇦'),
('zh','Chinese','🇿🇭'),
('zu','Zulu','🇿🇺');
